- CONTRIBUTING.md
- README.md
Hello, I noticed that the name of your project was wrong, so I updated it for you :smiley:
> Update name of the project

- src/exceptions.py
- src/main.py
- src/ooc.py
An exception file was added in case custom exceptions need to be done in the future
> Better exception handling

- src/DownloadableCharactersScreen.py
- src/character.py
- src/characters/Narrator/settings.ini
- src/characters/RedHerring/settings.ini
- src/irc_mo.py
- src/mainscreen.py
- Non-Drive link support
- Allowed for updates of existing characters via version system
- Function that removes all files that are not png, atlas or ini files (easiest way to clean it up).
- A chunk of my soul forever lost.
> DLC changes

- src/commands.py
- src/inventory.py
- src/irc_mo.py
- src/main.py
- src/ooc.py
- Non-imgur URLs work for inventory by manually downloading the image then displaying it from the local copy instead of using AsyncImage to download it, which was causing the issue to begin with (thanks, Kivy).
- Clear works based on your location now, meaning it's not serverwide as before.
- Cleaned up music a tiny bit (fucking Discord links).
> Inventory & Clear

- src/ooc.py
> allows for non-ascii file names

- src/sprite.py
> Shallow copy textures in sprites before returning it

- src/commands.py
For now, it only shows a list of available commands when entering /help
> Adds a basic help command.

- src/user.py
Basically, I made it so a red herring sprite is returned if character is none and I also made it so characters dictionary is never cleaned. (Its update method takes care of updateing everything for us, so we don't need to clean it.)
> Attempt to fix DLC crash

- src/irc_mo.py
- src/sprite.py
I've spent so much fucking time for this fix oh god fuck python oh no fuck kivy also MO 2.0 superior programming language C# edition when
> Fix nullposting in different location screwing CGs you can't nullpost with CGs anymore

- src/inventory.py
Fixes this [crash](https://github.com/Moe-Team/MysteryOnline/files/3804458/MO_19-11-03_3.txt).
And also should be more efficient.
> Fix inventory crash

- src/irc_mo.py
- src/kv_files/sprite.kv
- src/user.py
Also makes it so new people can see where everyone was. Whoo!
> Send nullpost when someone connects to prevent sprites from disappearing

- src/irc_mo.py
- src/kv_files/user_box.kv
- src/location.py
- src/main.py
- src/ooc.py
- src/sprite.py
- src/user.py
- src/user_box.py
Relevant changes:
- Fixed bug that made everyone disappear when someone connected
- Fixed bug where sublocations weren't updated correctly when users were in different locations
- Added W A R P
- Made it so everyone nullposts when someone joins, so they can see where everyone was
- lots of other stuff
> W a r p and now people who join will be able to see where everyone was

- src/__init__.py
- src/loginscreen.py
- src/main.py
Mostly useful for development/debugging, and people who don't want to click on the log in button for some reason.
> Add autoconnect with --connect parameter

- src/sprite.py
> Fix foreground

- src/irc_mo.py
- src/location.py
this was supposed to also include the return -> continue fix but eh
> Fix crash when you join at the same time as someone disconnects

- src/ooc.py
something about volume, this fixes it tho
> Fix youtube music on new kivy

- src/inventory.py
- src/kv_files/mopopup.kv
- src/mopopup.py
- tests/test_form_popup.py
Cause we really need it, specifically for item creation.
Look @Unbancho, I used PROPERTIES (pls review)
> Add a new form-like popup

- MysteryOnline/__init__.py
- MysteryOnline/loginscreen.py
- kv_files/loginscreen.kv
> Program version is updated by code instead

- MysteryOnline/ooc.py
Also fixes all crashes relating to music.
This is painful.
> Reintroduce multiple songs at once bug, but make reset music button work

- MysteryOnline/ooc.py
LIFE IS PAIN, PYTHON IS TERRIBLE
> Music is now downloaded to a temporary directory.

- MysteryOnline/main.py
- MysteryOnline/ooc.py
Also make it so sound doesn't play if volume is 0 to fix a bug and attempts to kill all tracks on exit so threads kill themselves. Will see about the logarithmic volume stuff later.
> Tuturu fix 

- MysteryOnline/irc_mo.py
- MysteryOnline/loginscreen.py
- irc_channel_name.ini
and by sekrit clubs I mean channels locked with passwords
> Add sekrit clubs, better irc_channel_name.ini parsing

- MysteryOnline/character.py
- MysteryOnline/inventory.py
- MysteryOnline/irc_mo.py
- MysteryOnline/mainscreen.py
- MysteryOnline/set_kivy_config.py
Allows for version to be used instead of ver for the dlc feature in the ini.
Also another exception to catch that refresh bug just in case.
And one for a wild inventory crash that happened.
I've got no idea how the logger work so I hope I did good by copying Zumo's thing.
> Exceptions and ini tweak
